### ISSUE TITLE
The license for the project is not defined/clear

### ISSUE THREAD

**Issue by it-praktyk** [trondhindenes/AnsibleDscModuleGenerator#4]
Hi

In the AnsibleDscModuleGenerator a license is not declared in a clear way. 

Based on remarks in the files located in the subdirectory PlaceHolderFiles I assume that GNU GPL v. 3 is that license but it should be declared.

Additional link https://help.github.com/articles/open-source-licensing/

**Comment by trondhindenes** [comment]
hi! Thanks, I'll add a license file

**Comment by trondhindenes** [comment]
Added MIT license. Sorry it took so long. Closing.
