### ISSUE TITLE
The DscModuleName parameter should not be mandatory

### ISSUE THREAD

**Issue by it-praktyk** [trondhindenes/AnsibleDscModuleGenerator#9]
The parameter currently is marked as mandatory. But for some resources the name of module is not fullfiled by Microsoft - e.g.

```
PS > Get-DscResource -Name file | fl

ResourceType  : MSFT_FileDirectoryConfiguration
Name          : File
FriendlyName  : File
Module        :
ModuleName    :
Version       :
Path          :
ParentPath    : C:\Windows\system32\Configuration\Schema\MSFT_FileDirectoryConfiguration
ImplementedAs : Binary
CompanyName   :
Properties    : {DestinationPath, Attributes, Checksum, Contents...}
```

BTW, the example included in the current version of code should throw execption :-)

**Comment by trondhindenes** [comment]
The file resource is weird, and as far as I know the only resource which doesnt belong in a module. For this reason it's impossible to invoke "File" resources using Invoke-DscResource, which is what is used under the covers. 

So in short: Won't fix, because it's not fixable :-(
